name: Rebuild index.db

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0,6,12,18 * * *'
  workflow_dispatch:
    inputs:
      skip_fetch_data:
        type: boolean
        default: true
        description: 'Skip the Fetch Data step'

env:
  IMAGE_TAR_NAME: "dev-image.tar"
    
jobs:
  rebuild_index:
    name: Rebuild index.db
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Dashboard Repository
        uses: actions/checkout@v4

      # prepare development image
      - name: Get the SHA of the last commit
        id: cache_key
        run: |
          echo "key=$(md5sum ./Dockerfile |cut -f1 -d' ')" >> $GITHUB_OUTPUT
      
      - name: Restore The Dev Image
        id: cache
        uses: actions/cache/restore@v4
        with:
          key: ${{ steps.cache_key.outputs.key }}
          path: ${{ env.IMAGE_TAR_NAME }}

      - name: Load The Dev Image
        if: steps.cache.outputs.cache-hit == 'true'
        run: |
          ./run.sh load_image "$IMAGE_TAR_NAME"

      - name: Build The Dev Image
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          ./run.sh save_image "$IMAGE_TAR_NAME"
          ls -l "$IMAGE_TAR_NAME"

      - name: Cache The Dev Image
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/cache@v4
        with:
          key: ${{ steps.cache_key.outputs.key }}
          path: ${{ env.IMAGE_TAR_NAME }}

      # Setup the repository
      - name: Setup the repository
        run: |
          ./run.sh setup

      # fetch data and build index
      - name: Fetch Data
        if: ${{ !github.event.inputs.skip_fetch_data && github.event_name != 'push' }}
        # env:
          # GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./run.sh update_data

      - name: Compile Index
        run: |
          ./run.sh update_index

      - name: Build Dashboard
        if: ${{ github.event_name == 'push' }}
        run: |
          ./run.sh build_site

      - name: Push Dist
        run: |
          cp index.db dashboard/dist/index.db
          cp index.db.br dashboard/dist/index.db.br # just incase we do not rebuild the dashboard
          ./run.sh push_dist "Automatic Dist Update"